DROP TABLE post IF EXISTS;
DROP TABLE user IF EXISTS;


CREATE TABLE user 
(
  id INTEGER NOT NULL,
  email_id CHARACTER VARYING(30) NOT NULL,
  name CHARACTER VARYING(30) NOT NULL,
  CONSTRAINT iduser PRIMARY KEY (id)
);

CREATE TABLE post 
(
  id INTEGER NOT NULL,
  title CHARACTER VARYING(30) NOT NULL,
  content CHARACTER VARYING(100) NOT NULL,
  created_on CHARACTER VARYING(30) NOT NULL,
  user_id INTEGER NOT NULL,
  CONSTRAINT idposts PRIMARY KEY (id)
);

ALTER TABLE
    post ADD CONSTRAINT post FOREIGN KEY (user_id) REFERENCES user (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE